[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_18"]

[phases.build]
dependsOn = ["setup"]
cmds = ["bash build.sh"]

[start]
cmd = "python3 backend/manage.py migrate && python3 backend/manage.py seed_data && gunicorn --pythonpath backend --bind 0.0.0.0:$PORT --timeout 600 incident_system.wsgi"
